import {
  AdminNotification,
  Category,
  Coupon,
  Customer,
  Order,
  Product,
  Review,
  StoreSettings,
  User,
} from '../types';

export const INITIAL_SETTINGS: StoreSettings = {
  storeName: 'Ali Online Store',
  logoText: 'Ali Store',
  description: "Pakistan's trusted premium online store for trending gadgets, electronics, fashion and lifestyle essentials.",
  phone: '+92 300 7654321',
  email: 'alisahab62525@gmail.com',
  whatsapp: '+923007654321',
  address: 'Shop 14-B, Commercial Plaza, Gulberg III, Lahore, Pakistan',
  businessHours: 'Monday – Saturday: 9:00 AM – 9:00 PM (PKT)',
  currency: 'PKR',
  deliveryFee: 250,
  freeDeliveryThreshold: 3500,
  socialLinks: {
    facebook: 'https://facebook.com/alionlinestore',
    instagram: 'https://instagram.com/alionlinestore',
    twitter: 'https://twitter.com/alionlinestore',
  },
  paymentInstructions: {
    cod: 'Pay with cash upon package arrival at your doorstep. Please keep exact change ready.',
    bankTransfer: 'Meezan Bank Ltd | Title: Ali Online Store | Account: 0291-0103982901 | IBAN: PK65MEZN0002910103982901. Share screenshot via WhatsApp.',
    jazzCash: 'JazzCash Mobile Account: 0300-7654321 (Title: Ali Store). Send transaction ID in order notes.',
    easypaisa: 'Easypaisa Mobile Account: 0312-9876543 (Title: Ali Store). Share SMS receipt via WhatsApp.',
  },
};

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    name: 'Smartphones & Accessories',
    slug: 'smartphones-accessories',
    description: 'Latest mobile phones, premium cases, fast chargers & MagSafe accessories.',
    image: 'https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?auto=format&fit=crop&w=800&q=80',
    productCount: 4,
    isActive: true,
  },
  {
    id: 'cat-2',
    name: 'Audio & Wearables',
    slug: 'audio-wearables',
    description: 'Active noise cancellation earbuds, studio headphones & smart fitness watches.',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
    productCount: 4,
    isActive: true,
  },
  {
    id: 'cat-3',
    name: "Men's Apparel & Fashion",
    slug: 'mens-apparel',
    description: 'Tailored luxury polos, everyday tees, jackets & genuine leather accessories.',
    image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
    productCount: 3,
    isActive: true,
  },
  {
    id: 'cat-4',
    name: 'Home & Kitchen Essentials',
    slug: 'home-kitchen',
    description: 'Smart kitchen appliances, ambient lighting & ergonomic workspace gear.',
    image: 'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?auto=format&fit=crop&w=800&q=80',
    productCount: 3,
    isActive: true,
  },
  {
    id: 'cat-5',
    name: 'Luxury Fragrances',
    slug: 'perfumes-fragrances',
    description: 'Signature eau de parfums, pure oud blends & long-lasting artisanal scents.',
    image: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&w=800&q=80',
    productCount: 3,
    isActive: true,
  },
  {
    id: 'cat-6',
    name: 'Laptops & Computing',
    slug: 'laptops-computing',
    description: 'Mechanical keyboards, ultra-fast SSDs, precision mice & workstation docks.',
    image: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=800&q=80',
    productCount: 3,
    isActive: true,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    sku: 'ALI-AUD-001',
    name: 'AcousticPro ANC Wireless Earbuds',
    slug: 'acousticpro-anc-wireless-earbuds',
    description: 'Experience deep immersive sound with 45dB Active Noise Cancellation, custom 11mm graphene drivers, spatial audio support, and up to 38 hours of combined battery backup with fast wireless charging case.',
    shortDescription: '45dB Hybrid ANC, 38h battery life & IPX5 sweat resistance.',
    price: 6499,
    discountPrice: 4999,
    discountPercentage: 23,
    images: [
      'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1572536147248-ac59a8abfa4b?auto=format&fit=crop&w=900&q=80',
    ],
    categoryId: 'cat-2',
    categoryName: 'Audio & Wearables',
    brand: 'AcousticSound',
    stockQuantity: 42,
    stockStatus: 'in_stock',
    lowStockThreshold: 10,
    colors: ['Midnight Black', 'Pearl White', 'Nordic Blue'],
    specifications: [
      { key: 'Noise Cancellation', value: '45dB Hybrid ANC' },
      { key: 'Battery Life', value: '8.5h (Earbuds) + 30h (Case)' },
      { key: 'Bluetooth Version', value: '5.3 with AAC/LDAC' },
      { key: 'Water Resistance', value: 'IPX5 Sweat & Splash' },
    ],
    tags: ['anc', 'earbuds', 'wireless', 'bluetooth', 'audio'],
    rating: 4.8,
    reviewsCount: 38,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    isActive: true,
    createdAt: '2026-08-10T10:00:00Z',
    updatedAt: '2026-09-20T14:30:00Z',
  },
  {
    id: 'prod-2',
    sku: 'ALI-WTC-002',
    name: 'Apex AMOLED Smart Fitness Watch',
    slug: 'apex-amoled-smart-fitness-watch',
    description: 'Equipped with a 1.43-inch Always-On Retina AMOLED display, zinc-alloy unibody, SpO2 sensor, continuous heart rate monitor, Bluetooth calling, and 110+ professional sports modes.',
    shortDescription: '1.43" AMOLED, BT calling, 12-day battery & SpO2 health tracking.',
    price: 8999,
    discountPrice: 6999,
    discountPercentage: 22,
    images: [
      'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=900&q=80',
    ],
    categoryId: 'cat-2',
    categoryName: 'Audio & Wearables',
    brand: 'ApexTech',
    stockQuantity: 18,
    stockStatus: 'in_stock',
    lowStockThreshold: 8,
    colors: ['Titanium Gray', 'Obsidian Black', 'Desert Gold'],
    specifications: [
      { key: 'Display', value: '1.43" Ultra AMOLED 466x466' },
      { key: 'Battery', value: '410mAh (12 Days typical use)' },
      { key: 'Sensors', value: 'Heart Rate, SpO2, Sleep, Pedometer' },
      { key: 'Calling', value: 'Built-in Mic & Speaker HD Calling' },
    ],
    tags: ['smartwatch', 'fitness', 'amoled', 'wearable', 'health'],
    rating: 4.7,
    reviewsCount: 29,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: true,
    isActive: true,
    createdAt: '2026-08-15T12:00:00Z',
    updatedAt: '2026-09-22T09:15:00Z',
  },
  {
    id: 'prod-3',
    sku: 'ALI-CHG-003',
    name: 'GaN 65W Ultra-Fast 3-Port Turbo Charger',
    slug: 'gan-65w-ultra-fast-3-port-turbo-charger',
    description: 'Next-generation Gallium Nitride (GaN III) fast wall charger with 2 USB-C and 1 USB-A ports. Powers laptops, MacBooks, tablets, and smartphones simultaneously with smart temperature control.',
    shortDescription: '65W GaN III technology, dual USB-C + USB-A multi-port output.',
    price: 3499,
    discountPrice: 2699,
    discountPercentage: 23,
    images: [
      'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1622445268067-15d2a9386333?auto=format&fit=crop&w=900&q=80',
    ],
    categoryId: 'cat-1',
    categoryName: 'Smartphones & Accessories',
    brand: 'VoltCharge',
    stockQuantity: 55,
    stockStatus: 'in_stock',
    lowStockThreshold: 15,
    colors: ['Matte Black', 'Arctic White'],
    specifications: [
      { key: 'Total Wattage', value: '65W Max Power Delivery' },
      { key: 'Ports', value: '2x Type-C PD 3.0, 1x USB-A QC 4.0' },
      { key: 'Protection', value: 'Overvoltage, Overheat & Short-circuit' },
    ],
    tags: ['charger', 'gan', 'fast-charging', 'type-c', 'mobile-accessories'],
    rating: 4.9,
    reviewsCount: 52,
    isFeatured: false,
    isBestSeller: true,
    isNewArrival: false,
    isActive: true,
    createdAt: '2026-07-20T11:00:00Z',
    updatedAt: '2026-09-18T16:00:00Z',
  },
  {
    id: 'prod-4',
    sku: 'ALI-MAG-004',
    name: 'MagSafe 10,000mAh Magnetic Power Bank',
    slug: 'magsafe-10000mah-magnetic-power-bank',
    description: 'Snap-on wireless magnetic power bank designed for seamless iPhone 12/13/14/15/16 and Qi2 wireless phones. Features foldable kickstand and 20W PD wired fast charging port.',
    shortDescription: '15W wireless snap charging + 20W PD wired output with kickstand.',
    price: 4999,
    discountPrice: 3850,
    discountPercentage: 23,
    images: [
      'https://images.unsplash.com/photo-1609592424109-dd9892f1b177?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1618556658017-fd9c732d1360?auto=format&fit=crop&w=900&q=80',
    ],
    categoryId: 'cat-1',
    categoryName: 'Smartphones & Accessories',
    brand: 'VoltCharge',
    stockQuantity: 4,
    stockStatus: 'low_stock',
    lowStockThreshold: 5,
    colors: ['Space Gray', 'Alpine Silver'],
    specifications: [
      { key: 'Capacity', value: '10,000mAh Lithium Polymer' },
      { key: 'Wireless Output', value: '15W Max Magnetic Snap' },
      { key: 'Wired Output', value: '20W PD Type-C bidirectional' },
    ],
    tags: ['powerbank', 'magsafe', 'wireless-charger', 'portable-battery'],
    rating: 4.6,
    reviewsCount: 21,
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: true,
    isActive: true,
    createdAt: '2026-09-01T08:30:00Z',
    updatedAt: '2026-09-24T10:00:00Z',
  },
  {
    id: 'prod-5',
    sku: 'ALI-PRF-005',
    name: 'Oud Al-Maliki Extrait De Parfum (100ml)',
    slug: 'oud-al-maliki-extrait-de-parfum-100ml',
    description: 'A captivating blend of royal Cambodian agarwood, velvety Damascus rose, warm amber, and smoky leather. Formulated at 30% oil concentration for an unmatched 24-hour sillage.',
    shortDescription: 'Regal oud, Bulgarian rose & ambergris. 30% pure perfume oil concentration.',
    price: 7500,
    discountPrice: 5800,
    discountPercentage: 23,
    images: [
      'https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=900&q=80',
    ],
    categoryId: 'cat-5',
    categoryName: 'Luxury Fragrances',
    brand: 'Royal Attar Paris',
    stockQuantity: 24,
    stockStatus: 'in_stock',
    lowStockThreshold: 6,
    specifications: [
      { key: 'Volume', value: '100ml / 3.4 fl. oz.' },
      { key: 'Concentration', value: 'Extrait De Parfum (30% oil)' },
      { key: 'Top Notes', value: 'Saffron, Bergamot, Pink Peppercorn' },
      { key: 'Heart Notes', value: 'Taif Rose, Pure Cambodian Oud' },
      { key: 'Base Notes', value: 'Amber, White Musk, Cedarwood' },
    ],
    tags: ['perfume', 'oud', 'fragrance', 'luxury', 'scent'],
    rating: 4.9,
    reviewsCount: 46,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    isActive: true,
    createdAt: '2026-07-15T15:00:00Z',
    updatedAt: '2026-09-12T11:00:00Z',
  },
  {
    id: 'prod-6',
    sku: 'ALI-PRF-006',
    name: 'Ocean Breeze Fresh Aqua EDP (100ml)',
    slug: 'ocean-breeze-fresh-aqua-edp-100ml',
    description: 'Crisp Mediterranean sea notes mingled with Italian citrus, lavender, and mineral woods. Crisp, energetic, and endlessly versatile for warm days and executive meetings.',
    shortDescription: 'Crisp aquatic notes, bergamot & sun-drenched cedarwood.',
    price: 4500,
    discountPrice: 3499,
    discountPercentage: 22,
    images: [
      'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=900&q=80',
    ],
    categoryId: 'cat-5',
    categoryName: 'Luxury Fragrances',
    brand: 'Aura Parfums',
    stockQuantity: 15,
    stockStatus: 'in_stock',
    lowStockThreshold: 5,
    specifications: [
      { key: 'Volume', value: '100ml' },
      { key: 'Type', value: 'Eau De Parfum' },
      { key: 'Longevity', value: '10-12 Hours' },
    ],
    tags: ['perfume', 'fresh', 'aqua', 'summer', 'citrus'],
    rating: 4.7,
    reviewsCount: 19,
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: true,
    isActive: true,
    createdAt: '2026-08-25T14:00:00Z',
    updatedAt: '2026-09-21T09:00:00Z',
  },
  {
    id: 'prod-7',
    sku: 'ALI-APP-007',
    name: 'Classic Pique Cotton Oxford Polo Shirt',
    slug: 'classic-pique-cotton-oxford-polo-shirt',
    description: 'Crafted from 100% long-staple combed cotton pique fabric with anti-pilling treatment. Features mother-of-pearl buttons, ribbed collar that retains shape, and tailored athletic fit.',
    shortDescription: '100% combed Egyptian pique cotton with shape-retention collar.',
    price: 2999,
    discountPrice: 2199,
    discountPercentage: 27,
    images: [
      'https://images.unsplash.com/photo-1581655353564-df123a1eb820?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1625910513413-722359404286?auto=format&fit=crop&w=900&q=80',
    ],
    categoryId: 'cat-3',
    categoryName: "Men's Apparel & Fashion",
    brand: 'Monarch Heritage',
    stockQuantity: 35,
    stockStatus: 'in_stock',
    lowStockThreshold: 8,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Navy Blue', 'Forest Green', 'Burgundy', 'Charcoal'],
    specifications: [
      { key: 'Material', value: '100% Pique Cotton (230 GSM)' },
      { key: 'Fit', value: 'Modern Athletic Fit' },
      { key: 'Care', value: 'Machine wash cold, tumble dry low' },
    ],
    tags: ['polo', 'shirt', 'cotton', 'menswear', 'casual'],
    rating: 4.8,
    reviewsCount: 41,
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: false,
    isActive: true,
    createdAt: '2026-07-10T10:00:00Z',
    updatedAt: '2026-09-15T12:00:00Z',
  },
  {
    id: 'prod-8',
    sku: 'ALI-APP-008',
    name: 'Full-Grain Handcrafted Leather Bi-Fold Wallet',
    slug: 'full-grain-handcrafted-leather-bi-fold-wallet',
    description: 'Handmade from certified vegetable-tanned top-grain cowhide leather with RFID blocking foil lining. Features 8 dedicated card slots, 2 cash compartments, and discreet coin pouch.',
    shortDescription: 'Hand-stitched genuine leather with integrated RFID identity protection.',
    price: 2800,
    discountPrice: 1950,
    discountPercentage: 30,
    images: [
      'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=900&q=80',
    ],
    categoryId: 'cat-3',
    categoryName: "Men's Apparel & Fashion",
    brand: 'Monarch Heritage',
    stockQuantity: 28,
    stockStatus: 'in_stock',
    lowStockThreshold: 6,
    colors: ['Cognac Tan', 'Dark Espresso', 'Classic Black'],
    specifications: [
      { key: 'Leather', value: '100% Vegetable-Tanned Cowhide' },
      { key: 'Security', value: 'RFID Shielding 13.56 MHz' },
      { key: 'Slots', value: '8 Card Slots, 2 Bill Dividers' },
    ],
    tags: ['wallet', 'leather', 'accessories', 'rfid', 'gift'],
    rating: 4.9,
    reviewsCount: 33,
    isFeatured: false,
    isBestSeller: true,
    isNewArrival: false,
    isActive: true,
    createdAt: '2026-08-01T11:00:00Z',
    updatedAt: '2026-09-19T14:00:00Z',
  },
  {
    id: 'prod-9',
    sku: 'ALI-KBD-009',
    name: 'Nexus RGB Mechanical Wireless Keyboard',
    slug: 'nexus-rgb-mechanical-wireless-keyboard',
    description: 'Compact 75% hot-swappable mechanical gaming & typing keyboard with factory pre-lubed linear switches, gasket mounted structure, sound-dampening silicone foam, and tri-mode connectivity (Bluetooth 5.1 / 2.4GHz / Type-C).',
    shortDescription: 'Gasket-mounted 75% layout, pre-lubed switches & multi-device pairing.',
    price: 13500,
    discountPrice: 10999,
    discountPercentage: 19,
    images: [
      'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&w=900&q=80',
    ],
    categoryId: 'cat-6',
    categoryName: 'Laptops & Computing',
    brand: 'NexusPrecision',
    stockQuantity: 12,
    stockStatus: 'in_stock',
    lowStockThreshold: 4,
    colors: ['Retro Beige', 'Cyber Gray'],
    specifications: [
      { key: 'Layout', value: '75% (82 Keys) ANSI' },
      { key: 'Switches', value: 'Hot-Swap Factory Lubed Linear Gateron' },
      { key: 'Mount', value: 'Double Gasket Silicone Dampened' },
      { key: 'Battery', value: '4000mAh Rechargeable' },
    ],
    tags: ['keyboard', 'mechanical', 'rgb', 'gaming', 'wireless'],
    rating: 4.9,
    reviewsCount: 27,
    isFeatured: true,
    isBestSeller: false,
    isNewArrival: true,
    isActive: true,
    createdAt: '2026-08-20T16:00:00Z',
    updatedAt: '2026-09-23T11:30:00Z',
  },
  {
    id: 'prod-10',
    sku: 'ALI-MOU-010',
    name: 'GlidePro Ergonomic Precision Wireless Mouse',
    slug: 'glidepro-ergonomic-precision-wireless-mouse',
    description: 'Designed for extended productivity and wrist comfort with contoured thumb rest, dual magnetic scroll wheel with free-spin mode, silent click switches, and 8,000 DPI sensor tracking on glass.',
    shortDescription: 'Ergonomic sculpt, hyper-scroll wheel & whisper-quiet switches.',
    price: 6500,
    discountPrice: 4850,
    discountPercentage: 25,
    images: [
      'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=900&q=80',
    ],
    categoryId: 'cat-6',
    categoryName: 'Laptops & Computing',
    brand: 'NexusPrecision',
    stockQuantity: 21,
    stockStatus: 'in_stock',
    lowStockThreshold: 5,
    colors: ['Graphite', 'Off-White'],
    specifications: [
      { key: 'Sensor', value: 'Darkfield 8000 DPI Laser' },
      { key: 'Connectivity', value: 'Bluetooth LE + 2.4GHz USB Dongle' },
      { key: 'Battery', value: 'Up to 70 days per charge' },
    ],
    tags: ['mouse', 'ergonomic', 'wireless', 'office', 'computing'],
    rating: 4.7,
    reviewsCount: 18,
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: false,
    isActive: true,
    createdAt: '2026-07-28T13:00:00Z',
    updatedAt: '2026-09-14T10:00:00Z',
  },
  {
    id: 'prod-11',
    sku: 'ALI-HOM-011',
    name: 'Smart Aroma Essential Oil Ultrasonic Diffuser',
    slug: 'smart-aroma-essential-oil-ultrasonic-diffuser',
    description: '500ml capacity ultrasonic cool mist aroma humidifier with realistic flame LED ambience, timer intervals (1h/3h/6h), automatic waterless shutoff protection, and ultra-quiet 20dB whisper operation.',
    shortDescription: '500ml ultrasonic cool mist with flame ambience & auto-off safety.',
    price: 4200,
    discountPrice: 3150,
    discountPercentage: 25,
    images: [
      'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=900&q=80',
    ],
    categoryId: 'cat-4',
    categoryName: 'Home & Kitchen Essentials',
    brand: 'LuminaHome',
    stockQuantity: 19,
    stockStatus: 'in_stock',
    lowStockThreshold: 6,
    colors: ['Natural Oak', 'Matte Black'],
    specifications: [
      { key: 'Capacity', value: '500ml Tank' },
      { key: 'Mist Output', value: '30-50 ml/hour' },
      { key: 'Coverage', value: 'Up to 350 sq. ft.' },
      { key: 'Noise Level', value: '< 20dB' },
    ],
    tags: ['diffuser', 'aromatherapy', 'home', 'humidifier', 'lifestyle'],
    rating: 4.8,
    reviewsCount: 25,
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: true,
    isActive: true,
    createdAt: '2026-08-30T10:00:00Z',
    updatedAt: '2026-09-21T15:00:00Z',
  },
  {
    id: 'prod-12',
    sku: 'ALI-HOM-012',
    name: 'Precision Barista Electric Gooseneck Kettle',
    slug: 'precision-barista-electric-gooseneck-kettle',
    description: '1.0L matte black stainless steel gooseneck pour-over kettle with 1200W rapid boil element, precision 1°C temperature dial, real-time LCD readout, and 60-minute heat maintain mode.',
    shortDescription: '1200W rapid heating, 1°C precision temp dial & ergonomic balanced spout.',
    price: 9800,
    discountPrice: 7999,
    discountPercentage: 18,
    images: [
      'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=900&q=80',
    ],
    categoryId: 'cat-4',
    categoryName: 'Home & Kitchen Essentials',
    brand: 'BaristaCraft',
    stockQuantity: 3,
    stockStatus: 'low_stock',
    lowStockThreshold: 5,
    specifications: [
      { key: 'Capacity', value: '1.0 Liter' },
      { key: 'Power', value: '1200W Strix Heating Element' },
      { key: 'Material', value: 'Food-Grade 304 Stainless Steel' },
    ],
    tags: ['kettle', 'coffee', 'kitchen', 'tea', 'barista'],
    rating: 4.9,
    reviewsCount: 31,
    isFeatured: true,
    isBestSeller: false,
    isNewArrival: false,
    isActive: true,
    createdAt: '2026-08-05T09:00:00Z',
    updatedAt: '2026-09-17T11:00:00Z',
  },
  {
    id: 'prod-13',
    sku: 'ALI-PHN-013',
    name: 'Ultra-Clear 9H Tempered Glass Screen Guard (2-Pack)',
    slug: 'ultra-clear-9h-tempered-glass-screen-guard',
    description: 'Double ion-exchange tempered glass with edge-to-edge curved chamfer, oleophobic fingerprint-resistant coating, auto-alignment installation frame, and 99.9% optical transparency.',
    shortDescription: '2-Pack military-grade 9H hardness with auto-alignment install tray.',
    price: 1200,
    discountPrice: 850,
    discountPercentage: 29,
    images: [
      'https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?auto=format&fit=crop&w=900&q=80',
    ],
    categoryId: 'cat-1',
    categoryName: 'Smartphones & Accessories',
    brand: 'ShieldArmor',
    stockQuantity: 110,
    stockStatus: 'in_stock',
    lowStockThreshold: 20,
    specifications: [
      { key: 'Hardness', value: '9H Sapphire Certified' },
      { key: 'Thickness', value: '0.33mm Ultra-thin' },
      { key: 'Package', value: '2x Glass, 2x Cleaning Kit, 1x Alignment Tray' },
    ],
    tags: ['screen-protector', 'tempered-glass', 'iphone', 'samsung', 'accessories'],
    rating: 4.6,
    reviewsCount: 64,
    isFeatured: false,
    isBestSeller: true,
    isNewArrival: false,
    isActive: true,
    createdAt: '2026-06-15T12:00:00Z',
    updatedAt: '2026-09-10T14:00:00Z',
  },
  {
    id: 'prod-14',
    sku: 'ALI-AUD-014',
    name: 'Studio Wireless Over-Ear Hi-Res Headphones',
    slug: 'studio-wireless-over-ear-hi-res-headphones',
    description: 'Custom 40mm beryllium drivers delivering acoustic fidelity up to 40kHz. Plush memory foam earcups wrapped in breathable protein leather, 55 hours playback, and multipoint Bluetooth.',
    shortDescription: 'Hi-Res certified audio, 55h playback & ultra-soft memory cushions.',
    price: 14500,
    discountPrice: 11800,
    discountPercentage: 19,
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80',
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=900&q=80',
    ],
    categoryId: 'cat-2',
    categoryName: 'Audio & Wearables',
    brand: 'AcousticSound',
    stockQuantity: 8,
    stockStatus: 'in_stock',
    lowStockThreshold: 3,
    colors: ['Silver Sand', 'Obsidian Black'],
    specifications: [
      { key: 'Driver Size', value: '40mm Beryllium Diaphragm' },
      { key: 'Frequency Response', value: '10Hz – 40,000Hz' },
      { key: 'Battery', value: '55 Hours (Fast charge: 10m = 5 hours)' },
    ],
    tags: ['headphones', 'hi-res', 'wireless', 'over-ear', 'music'],
    rating: 4.9,
    reviewsCount: 34,
    isFeatured: true,
    isBestSeller: false,
    isNewArrival: true,
    isActive: true,
    createdAt: '2026-08-12T14:00:00Z',
    updatedAt: '2026-09-22T17:00:00Z',
  },
  {
    id: 'prod-15',
    sku: 'ALI-HOM-015',
    name: 'Minimalist LED Desk Lamp with Wireless Charging Base',
    slug: 'minimalist-led-desk-lamp-wireless-charging',
    description: 'Architectural aluminum task lamp with 5 color temperature presets (2700K - 6500K), smooth stepless dimming touch slider, flicker-free eye care technology, and integrated 10W wireless charging pad.',
    shortDescription: 'Flicker-free eye-care lighting, 5 color modes & 10W Qi charger base.',
    price: 5200,
    discountPrice: 3999,
    discountPercentage: 23,
    images: [
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&q=80',
    ],
    categoryId: 'cat-4',
    categoryName: 'Home & Kitchen Essentials',
    brand: 'LuminaHome',
    stockQuantity: 0,
    stockStatus: 'out_of_stock',
    lowStockThreshold: 5,
    colors: ['Matte Black', 'Silver'],
    specifications: [
      { key: 'Power Consumption', value: '14W LED + 10W Wireless Output' },
      { key: 'Color Temperatures', value: '2700K to 6500K' },
      { key: 'Arm Adjustment', value: '180° Foldable Dual-Joint' },
    ],
    tags: ['lamp', 'desk', 'wireless-charger', 'office', 'led'],
    rating: 4.7,
    reviewsCount: 16,
    isFeatured: false,
    isBestSeller: false,
    isNewArrival: false,
    isActive: true,
    createdAt: '2026-07-05T10:00:00Z',
    updatedAt: '2026-09-16T12:00:00Z',
  },
  {
    id: 'prod-16',
    sku: 'ALI-APP-016',
    name: 'Weatherproof Everyday Urban Commuter Backpack (22L)',
    slug: 'weatherproof-everyday-urban-commuter-backpack',
    description: 'Constructed from durable 840D ballistic recycled nylon with water-repellent DWR coating. Dedicated padded sleeve holds up to 16-inch laptops, hidden passport anti-theft pocket, and luggage pass-through strap.',
    shortDescription: 'Water-resistant 840D nylon, 16" laptop vault & luggage pass-through.',
    price: 5800,
    discountPrice: 4299,
    discountPercentage: 26,
    images: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=80',
    ],
    categoryId: 'cat-3',
    categoryName: "Men's Apparel & Fashion",
    brand: 'Monarch Heritage',
    stockQuantity: 16,
    stockStatus: 'in_stock',
    lowStockThreshold: 4,
    colors: ['Stealth Black', 'Navy Blue'],
    specifications: [
      { key: 'Capacity', value: '22 Liters' },
      { key: 'Laptop Compartment', value: 'Fits up to 16" MacBook Pro' },
      { key: 'Zippers', value: 'YKK Weather-Shield Inverted' },
    ],
    tags: ['backpack', 'commute', 'laptop-bag', 'travel', 'fashion'],
    rating: 4.8,
    reviewsCount: 22,
    isFeatured: false,
    isBestSeller: true,
    isNewArrival: false,
    isActive: true,
    createdAt: '2026-08-02T13:00:00Z',
    updatedAt: '2026-09-18T10:00:00Z',
  },
];

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: 'coup-1',
    code: 'WELCOME10',
    discountType: 'percentage',
    discountValue: 10,
    minOrderAmount: 2000,
    maxDiscountAmount: 1000,
    expiryDate: '2026-12-31T23:59:59Z',
    usageLimit: 500,
    usageCount: 42,
    isActive: true,
  },
  {
    id: 'coup-2',
    code: 'FLAT500',
    discountType: 'fixed',
    discountValue: 500,
    minOrderAmount: 3500,
    expiryDate: '2026-11-30T23:59:59Z',
    usageLimit: 200,
    usageCount: 18,
    isActive: true,
  },
  {
    id: 'coup-3',
    code: 'ALIEXCLUSIVE',
    discountType: 'percentage',
    discountValue: 15,
    minOrderAmount: 5000,
    maxDiscountAmount: 2000,
    expiryDate: '2026-12-15T23:59:59Z',
    usageLimit: 100,
    usageCount: 9,
    isActive: true,
  },
];

export const INITIAL_ADMIN: User = {
  id: 'usr-admin-1',
  name: 'Ali Sahab',
  email: 'alisahab62525@gmail.com',
  phone: '+92 300 7654321',
  role: 'admin',
  createdAt: '2026-01-01T00:00:00Z',
};

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'usr-cust-1',
    name: 'Ali Khan',
    email: 'customer@example.com',
    phone: '+92 300 1234567',
    role: 'customer',
    createdAt: '2026-07-01T10:00:00Z',
    defaultAddressId: 'addr-1',
    orderCount: 2,
    totalSpent: 11498,
    addresses: [
      {
        id: 'addr-1',
        customerId: 'usr-cust-1',
        label: 'Home',
        recipientName: 'Ali Khan',
        phone: '+92 300 1234567',
        streetAddress: 'House 42, Street 7, Block D, DHA Phase 5',
        city: 'Lahore',
        area: 'DHA Phase 5',
        postalCode: '54000',
        isDefault: true,
      },
      {
        id: 'addr-2',
        customerId: 'usr-cust-1',
        label: 'Work',
        recipientName: 'Ali Khan (Office)',
        phone: '+92 300 1234567',
        streetAddress: 'Floor 4, Arfa Software Technology Park, Ferozepur Road',
        city: 'Lahore',
        area: 'Nishtar Town',
        postalCode: '54600',
        isDefault: false,
      },
    ],
  },
  {
    id: 'usr-cust-2',
    name: 'Sara Ahmed',
    email: 'sara@example.com',
    phone: '+92 312 9876543',
    role: 'customer',
    createdAt: '2026-08-10T14:30:00Z',
    defaultAddressId: 'addr-3',
    orderCount: 1,
    totalSpent: 5800,
    addresses: [
      {
        id: 'addr-3',
        customerId: 'usr-cust-2',
        label: 'Home',
        recipientName: 'Sara Ahmed',
        phone: '+92 312 9876543',
        streetAddress: 'Apartment 302, Royal Residency, Clifton Block 2',
        city: 'Karachi',
        area: 'Clifton',
        postalCode: '75600',
        isDefault: true,
      },
    ],
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ALI-10025',
    customerId: 'usr-cust-1',
    customerName: 'Ali Khan',
    customerEmail: 'customer@example.com',
    customerPhone: '+92 300 1234567',
    deliveryAddress: {
      recipientName: 'Ali Khan',
      phone: '+92 300 1234567',
      streetAddress: 'House 42, Street 7, Block D, DHA Phase 5',
      city: 'Lahore',
      area: 'DHA Phase 5',
      postalCode: '54000',
      label: 'Home',
    },
    items: [
      {
        productId: 'prod-1',
        productName: 'AcousticPro ANC Wireless Earbuds',
        productImage: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=900&q=80',
        sku: 'ALI-AUD-001',
        unitPrice: 4999,
        quantity: 1,
        selectedColor: 'Midnight Black',
        subtotal: 4999,
      },
    ],
    subtotal: 4999,
    discountAmount: 0,
    deliveryFee: 0, // Above free delivery threshold (3500)
    grandTotal: 4999,
    paymentMethod: 'Cash on Delivery',
    paymentStatus: 'Pending',
    orderStatus: 'Confirmed',
    customerNotes: 'Please ring the bell twice upon arrival.',
    adminNotes: 'Order verified via phone with customer.',
    timeline: [
      {
        status: 'Pending',
        timestamp: '2026-09-26T15:20:00Z',
        note: 'Order placed by customer via Cash on Delivery.',
      },
      {
        status: 'Confirmed',
        timestamp: '2026-09-26T15:45:00Z',
        note: 'Customer contact verified. Queued for fulfillment.',
      },
    ],
    createdAt: '2026-09-26T15:20:00Z',
    updatedAt: '2026-09-26T15:45:00Z',
  },
  {
    id: 'ALI-10024',
    customerId: 'usr-cust-2',
    customerName: 'Sara Ahmed',
    customerEmail: 'sara@example.com',
    customerPhone: '+92 312 9876543',
    deliveryAddress: {
      recipientName: 'Sara Ahmed',
      phone: '+92 312 9876543',
      streetAddress: 'Apartment 302, Royal Residency, Clifton Block 2',
      city: 'Karachi',
      area: 'Clifton',
      postalCode: '75600',
      label: 'Home',
    },
    items: [
      {
        productId: 'prod-5',
        productName: 'Oud Al-Maliki Extrait De Parfum (100ml)',
        productImage: 'https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&w=900&q=80',
        sku: 'ALI-PRF-005',
        unitPrice: 5800,
        quantity: 1,
        subtotal: 5800,
      },
    ],
    subtotal: 5800,
    discountAmount: 0,
    deliveryFee: 0,
    grandTotal: 5800,
    paymentMethod: 'Bank Transfer',
    paymentStatus: 'Paid',
    orderStatus: 'Shipped',
    courier: 'TCS Express',
    trackingNumber: 'TCS-992148102',
    adminNotes: 'Payment verified in Meezan Bank account.',
    timeline: [
      {
        status: 'Pending',
        timestamp: '2026-09-25T11:00:00Z',
        note: 'Order submitted.',
      },
      {
        status: 'Confirmed',
        timestamp: '2026-09-25T11:30:00Z',
        note: 'Bank transfer screenshot confirmed.',
      },
      {
        status: 'Processing',
        timestamp: '2026-09-25T14:00:00Z',
        note: 'Bubble wrapped with fragile sticker.',
      },
      {
        status: 'Shipped',
        timestamp: '2026-09-26T09:00:00Z',
        note: 'Dispatched via TCS Express. Tracking: TCS-992148102',
      },
    ],
    createdAt: '2026-09-25T11:00:00Z',
    updatedAt: '2026-09-26T09:00:00Z',
  },
  {
    id: 'ALI-10023',
    customerId: 'usr-cust-1',
    customerName: 'Ali Khan',
    customerEmail: 'customer@example.com',
    customerPhone: '+92 300 1234567',
    deliveryAddress: {
      recipientName: 'Ali Khan',
      phone: '+92 300 1234567',
      streetAddress: 'House 42, Street 7, Block D, DHA Phase 5',
      city: 'Lahore',
      area: 'DHA Phase 5',
      postalCode: '54000',
      label: 'Home',
    },
    items: [
      {
        productId: 'prod-2',
        productName: 'Apex AMOLED Smart Fitness Watch',
        productImage: 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?auto=format&fit=crop&w=900&q=80',
        sku: 'ALI-WTC-002',
        unitPrice: 6999,
        quantity: 1,
        selectedColor: 'Obsidian Black',
        subtotal: 6999,
      },
    ],
    subtotal: 6999,
    discountAmount: 500,
    couponCode: 'FLAT500',
    deliveryFee: 0,
    grandTotal: 6499,
    paymentMethod: 'Cash on Delivery',
    paymentStatus: 'Paid',
    orderStatus: 'Delivered',
    courier: 'Leopards Courier',
    trackingNumber: 'LEO-4410982',
    timeline: [
      { status: 'Pending', timestamp: '2026-09-18T10:00:00Z' },
      { status: 'Confirmed', timestamp: '2026-09-18T10:30:00Z' },
      { status: 'Processing', timestamp: '2026-09-18T14:00:00Z' },
      { status: 'Shipped', timestamp: '2026-09-19T09:00:00Z' },
      { status: 'Delivered', timestamp: '2026-09-21T16:15:00Z', note: 'Customer accepted package and paid cash.' },
    ],
    createdAt: '2026-09-18T10:00:00Z',
    updatedAt: '2026-09-21T16:15:00Z',
  },
];

export const INITIAL_NOTIFICATIONS: AdminNotification[] = [
  {
    id: 'notif-1',
    type: 'new_order',
    title: 'New Order Received #ALI-10025',
    message: 'Ali Khan placed an order of Rs. 4,999 (Cash on Delivery).',
    orderId: 'ALI-10025',
    isRead: false,
    createdAt: '2026-09-26T15:20:00Z',
  },
  {
    id: 'notif-2',
    type: 'low_stock',
    title: 'Low Stock Alert',
    message: 'Precision Barista Electric Gooseneck Kettle has only 3 units remaining in stock.',
    productId: 'prod-12',
    isRead: false,
    createdAt: '2026-09-26T12:00:00Z',
  },
  {
    id: 'notif-3',
    type: 'new_order',
    title: 'New Order Received #ALI-10024',
    message: 'Sara Ahmed placed an order of Rs. 5,800 (Bank Transfer).',
    orderId: 'ALI-10024',
    isRead: true,
    createdAt: '2026-09-25T11:00:00Z',
  },
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    productId: 'prod-1',
    productName: 'AcousticPro ANC Wireless Earbuds',
    customerId: 'usr-cust-1',
    customerName: 'Ali Khan',
    rating: 5,
    comment: 'The noise cancellation is astonishing for this price point! Bass is punchy and microphone clarity on calls is super crisp.',
    isVerifiedPurchase: true,
    status: 'approved',
    createdAt: '2026-09-22T14:00:00Z',
  },
  {
    id: 'rev-2',
    productId: 'prod-5',
    productName: 'Oud Al-Maliki Extrait De Parfum (100ml)',
    customerId: 'usr-cust-2',
    customerName: 'Sara Ahmed',
    rating: 5,
    comment: 'Exquisite formulation. Lasts easily over 20 hours on clothes. Packaging was very secure and fast delivery!',
    isVerifiedPurchase: true,
    status: 'approved',
    createdAt: '2026-09-24T18:00:00Z',
  },
  {
    id: 'rev-3',
    productId: 'prod-2',
    productName: 'Apex AMOLED Smart Fitness Watch',
    customerId: 'usr-cust-1',
    customerName: 'Ali Khan',
    rating: 5,
    comment: 'The AMOLED screen is crystal clear even under intense sunlight. Battery lasts easily 10 days.',
    isVerifiedPurchase: true,
    status: 'approved',
    createdAt: '2026-09-23T11:00:00Z',
  },
];
